// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// To get th
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options for the web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFgIb-9rf0YtoApQhcb_PkUNwRl1MQbNo',
    appId: '1:909204974606:web:b4adcf63a412a443d3605f',
    messagingSenderId: '909204974606',
    projectId: 'docs-ai-192fb',
    authDomain: 'docs-ai-192fb.firebaseapp.com',
    storageBucket: 'docs-ai-192fb.appspot.com',
    measurementId: 'G-6RNBWMRGXB',
  );

  /// Firebase options for the Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc---6d5K5WY5BPQ6BWf70T1gW8EicpCc',
    appId: '1:909204974606:android:340480fd4f6473a5d3605f',
    messagingSenderId: '909204974606',
    projectId: 'docs-ai-192fb',
    storageBucket: 'docs-ai-192fb.appspot.com',
  );

  /// Firebase options for the iOS platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvzH07iSfuGUgX2n3jVNy32Fjog65gIE',
    appId: '1:909204974606:ios:7a72ef7ee06fae7dd3605f',
    messagingSenderId: '909204974606',
    projectId: 'docs-ai-192fb',
    storageBucket: 'docs-ai-192fb.appspot.com',
    iosBundleId: 'com.docsai.app',
  );
}
