# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

platform :ios do
  lane :deploy_debug do
    # Build iOS app
    gym(scheme: "Runner", configuration: "Debug")
    
    # Upload to Firebase Distribution
    firebase_app_distribution(
      app: "1:909204974606:ios:7a72ef7ee06fae7dd3605f",
      groups: "androidTesters",
      release_notes: "Debug build for testing"
    )
  end
end